services:
  - type: web
    name: carepoint-hospital-appointments
    runtime: docker
    dockerfilePath: ./Hospital_Appointment_Management_System/hospital_appointment_system/Dockerfile
    dockerContext: ./Hospital_Appointment_Management_System/hospital_appointment_system
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
